name: build-images-edge
concurrency:
  cancel-in-progress: true
  group: build-images-edge-${{ github.ref }}

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image-repo: ${{ github.repository_owner }}/py-spy
            context: ./services/py-spy
          - image-repo: ${{ github.repository_owner }}/memory-profiler
            context: ./services/memory-profiler
          - image-repo: ${{ github.repository_owner }}/profiler
            context: ./services/profiler
          - image-repo: ${{ github.repository_owner }}/restarter
            context: ./services/restarter
          - image-repo: ${{ github.repository_owner }}/linkerd-proxy-terminator
            context: ./services/linkerd-proxy-terminator
          - image-repo: ${{ github.repository_owner }}/email-validator
            context: ./services/email-validator
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU needed for Docker
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          logout: false
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
      - id: meta
        name: Docker metadata
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ matrix.image-repo }}
      - id: short-sha
        name: Set image tag
        run: |
          echo "short-sha=$(echo ${{ github.sha }} | cut -c 1-7 )" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ matrix.image-repo }}:${{ steps.short-sha.outputs.short-sha }}
            ${{ env.REGISTRY }}/${{ matrix.image-repo }}:latest
